### ISSUE TITLE
Iso-Area underestimates distance if line verticies are sparse

### ISSUE THREAD

**Issue by josephholler** [root676/QNEAT3#16]
In order to get more accurate Iso-Area results, users may need to densify their Network Layer input using the **Densify by interval** algorithm. 

I tested the algorithm by constructing a few very long lines with few vertices and calculating Iso-Areas at intervals that would fall in between distant vertices. Since the algorithm first calculates a point cloud using all the vertices in the network and _does not create any new points_ , it means that the outer-most iso-area contour or polygon may underestimate cost by as much as the longest segment of a line.

Most network inputs will already have reasonably dense vertices: this is only a problem if you have some very long, straight line segments.

E.g. see below, the 2500m Iso-Area point cloud and interpolation originating at the red hospital icon:
![image](https://user-images.githubusercontent.com/10039423/58643279-f19c4380-82cc-11e9-90fc-ac224a1a42d2.png)

and the same result after using Densify network:
![image](https://user-images.githubusercontent.com/10039423/58643554-7c7d3e00-82cd-11e9-8f3a-1f9e2b4ce720.png)
(I'm not sure what happened to the interpolation at the southern end of this figure... there are rows of _nodata_, but nonetheless you can see the difference in the point cloud)

**Comment by root676** [comment]
Thank you for pointing this out - I will still mark this as wontfix because it is the users responsibility to prepare his/her datasets in a reasonable manner (in the same way as with adding reasonable cost values or oneway information). This case is certainly not a common one and therefore has to be preprocessed by the user. Furthermore, adding the parameters for a user side densification would result in unnecessarily complex algorithm input UIs (...and they are already pretty complex).
