### ISSUE TITLE
Iso-Areas algorithms always throw error when (from Layer)

### ISSUE THREAD

**Issue by ghtmtt** [root676/QNEAT3#18]
I'm testing the plugin, especially the `Iso-Areas` algorithms. Using always the same line layer. 

Putting here some results:

* `Iso-Area as Contours (from Layer)`, when using a point layer with more than a single point I get:

```
Traceback (most recent call last):
File "/home/matteo/.local/share/QGIS/QGIS3/profiles/matteo/python/plugins/QNEAT3/algs/IsoAreaAsContoursFromLayer.py", line 255, in processAlgorithm
contour_featurelist = net.calcIsoContours(max_dist, interval, output_path)
File "/home/matteo/.local/share/QGIS/QGIS3/profiles/matteo/python/plugins/QNEAT3/Qneat3Framework.py", line 410, in calcIsoContours
band_in = ds_in.GetRasterBand(1)
AttributeError: 'NoneType' object has no attribute 'GetRasterBand'

Esecuzione fallita dopo 0.09 secondi
```

* `Iso-Area as Interpolation (from Layer)`: same as above. When a point layer with a single layer is used no problems,  while with more than 1 point same error of above.

I don't know if I'm missing some concepts or if this is not the intended behavior,

Cheers and thanks for the plugin

**Comment by root676** [comment]
Hi @ghtmtt, thanks for testing the QNEAT3 plugin! I just ran the two algorithms you mentioned on my windows machine: both tasks completed without errors. The error `AttributeError: 'NoneType' object has no attribute 'GetRasterBand'` usually pops up when you define very small iso area sizes so that no network nodes are reached and no interpolation can be performed. Which parameter values did you use? 

Judging from the paths in your error report, you are using Linux - I will try to test it on my ubuntu machine too.

**Comment by root676** [comment]
I tested the issue on my Linux machine but could not reproduce the error. I believe the error message is due to a small size value of the iso-area that has been chosen. I will take this as feedback to provide better feedback-messages for users in future releases.

**Comment by ghtmtt** [comment]
Thanks for taking care of this.
