### ISSUE TITLE
error in IsoAreaAsContoursFromPoint.py - TypeError: Input z must be at least a 2x2 array.

### ISSUE THREAD

**Issue by ramotswa** [root676/QNEAT3#41]
Input params;
{ 'CELL_SIZE' : 10, 'DEFAULT_DIRECTION' : 2, 'DEFAULT_SPEED' : 5, 'DIRECTION_FIELD' : '', 'ENTRY_COST_CALCULATION_METHOD' : 0, 'INPUT' : 'DIR/roadnetwork_utm44.shp|layername=roadnetwork_utm44', 'INTERVAL' : 50, 'MAX_DIST' : 100, 'OUTPUT_CONTOURS' : 'TEMPORARY_OUTPUT', 'OUTPUT_INTERPOLATION' : 'TEMPORARY_OUTPUT', 'SPEED_FIELD' : '', 'START_POINT' : '925206.685237,3066640.398371 [EPSG:24344]', 'STRATEGY' : 0, 'TOLERANCE' : 0, 'VALUE_BACKWARD' : '', 'VALUE_BOTH' : '', 'VALUE_FORWARD' : '' }

(Using a network in Nepal - and starting point in same projection). 

Any idea what I can do to fix this error? 
Thanks

**Comment by josephholler** [comment]
My best guess is to try increasing your short `MAX_DIST` of `100` (meters).  

I'm speculating... I haven't seen that particular error message before. This algorithm is creating a point cloud out of road network vertices within your `MAX_DIST` threshold, and then using a TIN interpolation to create a raster surface from those points. I've seen the TIN algorithm part of this fail in a case where the `MAX_DIST` was short and the points were all arranged on a straight line, so it failed to create any Delaunay Triangles with them. You could test this by using the `Pointcloud` version of the algorithm to see if you get any result. If you do get a result, try running the `TIN Interpolation` algorithm using your pointcloud as the input layer to see if that's where the issue is.
